const lang = {
  english: {
    Search: "Search",
    GPT_Placeholder: "What Would You  Like  To Watch Today ?",
    Logout: "Log Out",
    Home: "Home",
    GPT_Search: "GPT-Search",
    Play: "Play",
    MoreInfo: "More Info",
    NowPlayingMovies: "Now Playing Movies",
    UpCommingMovies: "UpComing Movies",
    TopRatedmovies: "Top Rated Movies",
    View_More: "View More",
    PopularMovies: "Popular Movies",
    FAQ: "FAQ",
    HelpCentre: "Help Centre",
    TermsofUse: "Terms of Use",
    Privacy: "Privacy",
    CookiePreferences: "Cookie Preferences",
    CorporateInformation: "Corporate Information",
    MediaCenter: "Media Center",
  },
  hindi: {
    Search: "खोज",
    GPT_Placeholder: "आप आज क्या देखना चाहेंगे?",
    Logout: "लॉग आउट",
    Home: "होम",
    GPT_Search: "जीपीटी-सर्च",
    Play: "खेल",
    MoreInfo: "अधिक जानकारी",
    NowPlayingMovies: "अब चल रही फिल्में",
    UpCommingMovies: "आगामी फिल्में",
    TopRatedmovies: "शीर्ष रेटेड फिल्में",
    View_More: "और देखें",
    PopularMovies: "लोकप्रिय फिल्में",
    FAQ: "अक्सर पूछे जाने वाले प्रश्न",
    HelpCentre: "सहायता केंद्र",
    TermsofUse: "उपयोग की शर्तें",
    Privacy: "गोपनीयता",
    CookiePreferences: "कुकी प्राथमिकताएं",
    CorporateInformation: "कॉर्पोरेट जानकारी",
    MediaCenter: "मीडिया केंद्र",
 
  },
  spanish: {
    Search: "Buscar",
    GPT_Placeholder: "Qué te gustaría ver hoy?",
    Logout: "Cerrar sesión",
    Home: "Hogar",
    GPT_Search: "Busqueda GPT",
    Play: "Reproducir", 
    MoreInfo: "Más información",
    NowPlayingMovies: "Películas en cartelera",
    UpCommingMovies: "Próximas películas",
    TopRatedmovies: "Películas mejor calificadas",
    View_More: "Ver más",
    PopularMovies: "Películas populares",
    FAQ: "Preguntas frecuentes",
    HelpCentre: "Centro de ayuda",
    TermsofUse: "Términos de uso",
    Privacy: "Privacidad",
    CookiePreferences: "Preferencias de cookies",
    CorporateInformation: "Información corporativa",
    MediaCenter: "Centro de medios",
  },
};
export default lang;
